-- The Composer: Coordinates the domains without harboring business logic.

local display = hl
local path = os.getenv("HOME")
local Browser = require("hyprland.browser")
local listen = require("hyprland.listen")

-- 1. Initialize monitors
display.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1.0
})

-- 2. Apply Configuration settings
display.config({
    autogenerated = false,

    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = {
                colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
                angle = 45
            },
            inactive_border = "rgba(595959aa)"
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle"
    },

    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)"
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696
        }
    },

    animations = {
        enabled = true,
        bezier = {
            "easeOutQuint,0.23,1,0.32,1",
            "easeInOutCubic,0.65,0.05,0.36,1",
            "linear,0,0,1,1",
            "almostLinear,0.5,0.5,0.75,1.0",
            "quick,0.15,0,0.1,1"
        },
        animation = {
            "global, 1, 10, default",
            "border, 1, 5.39, easeOutQuint",
            "windows, 1, 4.79, easeOutQuint",
            "windowsIn, 1, 4.1, easeOutQuint, popin 87%",
            "windowsOut, 1, 1.49, linear, popin 87%",
            "fadeIn, 1, 1.73, almostLinear",
            "fadeOut, 1, 1.46, almostLinear",
            "fade, 1, 3.03, quick",
            "layers, 1, 3.81, easeOutQuint",
            "layersIn, 1, 4, easeOutQuint, fade",
            "layersOut, 1, 1.5, linear, fade",
            "fadeLayersIn, 1, 1.79, almostLinear",
            "fadeLayersOut, 1, 1.39, almostLinear",
            "workspaces, 1, 1.94, almostLinear, fade",
            "workspacesIn, 1, 1.21, almostLinear, fade",
            "workspacesOut, 1, 1.94, almostLinear, fade"
        }
    },

    dwindle = {
        preserve_split = true
    },

    master = {
        new_status = "master"
    },

    misc = {
        force_default_wallpaper = 1,
        disable_hyprland_logo = false
    },

    input = {
        kb_layout = "fr",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false
        }
    },

    device = {
        {
            name = "epic-mouse-v1",
            sensitivity = -0.5
        }
    }
})

-- 3. Configure gestures and environment variables
display.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
display.env("XCURSOR_SIZE", "24")
display.env("HYPRCURSOR_SIZE", "24")

-- 4. Setup Lifecycle Hooks
display.on("hyprland.start", function ()
    display.exec_cmd("waybar -c " .. path .. "/.config/waybar/config.ini -s " .. path .. "/.config/waybar/style.css")
    display.exec_cmd("hyprpaper")
    display.exec_cmd("mako")
    display.exec_cmd("wl-paste --watch cliphist store")
    display.exec_cmd("wl-clipboard")
    display.exec_cmd("hypridle")
end)

-- 5. Domain Logic Hooks
display.on("window.open", function(window)
    Browser.isolate(window, display)
end)

-- 6. Apply Window Rules
display.window_rule({ match = { class = "^(Code|Windsurf|dev\\.zed\\.Zed|cursor)$" }, workspace = "2 silent" })
display.window_rule({ match = { class = "^(rio)$" }, workspace = "special:magic silent" })
display.window_rule({ match = { class = "^(thunar)$" }, float = true, center = true, size = { 800, 600 } })
display.window_rule({ match = { class = "^(rio)$" }, float = true, center = true, size = { 1000, 800 } })
display.window_rule({ match = { class = "^(localsend_app)$" }, float = true, center = true, size = { 800, 600 } })
display.window_rule({ match = { class = "^(blueman-manager)$" }, float = true, center = true, size = { 1000, 800 } })
display.window_rule({ match = { class = "^(org.telegram.desktop)$" }, float = true, center = true, size = { 1000, 800 } })
display.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
display.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false
    },
    no_focus = true
})

-- 7. Apply Keybindings
listen(display, path)
