-- #######################################################################################
-- HYPRLAND LUA CONFIGURATION
-- #######################################################################################

local home = os.getenv("HOME")

-- Monitors configuration
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1.0
})

-- Apply configuration settings
hl.config({
    autogenerated = false,

    -- Variables
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = {
                colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
                angle = 45
            },
            inactive_border = "rgba(595959aa)"
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle"
    },

    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)"
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696
        }
    },

    animations = {
        enabled = true,
        bezier = {
            "easeOutQuint,0.23,1,0.32,1",
            "easeInOutCubic,0.65,0.05,0.36,1",
            "linear,0,0,1,1",
            "almostLinear,0.5,0.5,0.75,1.0",
            "quick,0.15,0,0.1,1"
        },
        animation = {
            "global, 1, 10, default",
            "border, 1, 5.39, easeOutQuint",
            "windows, 1, 4.79, easeOutQuint",
            "windowsIn, 1, 4.1, easeOutQuint, popin 87%",
            "windowsOut, 1, 1.49, linear, popin 87%",
            "fadeIn, 1, 1.73, almostLinear",
            "fadeOut, 1, 1.46, almostLinear",
            "fade, 1, 3.03, quick",
            "layers, 1, 3.81, easeOutQuint",
            "layersIn, 1, 4, easeOutQuint, fade",
            "layersOut, 1, 1.5, linear, fade",
            "fadeLayersIn, 1, 1.79, almostLinear",
            "fadeLayersOut, 1, 1.39, almostLinear",
            "workspaces, 1, 1.94, almostLinear, fade",
            "workspacesIn, 1, 1.21, almostLinear, fade",
            "workspacesOut, 1, 1.94, almostLinear, fade"
        }
    },

    dwindle = {
        preserve_split = true
    },

    master = {
        new_status = "master"
    },

    misc = {
        force_default_wallpaper = 1,
        disable_hyprland_logo = false
    },

    input = {
        kb_layout = "fr",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false
        }
    },

    device = {
        {
            name = "epic-mouse-v1",
            sensitivity = -0.5
        }
    }
})

-- Configure Swipe gestures for workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Environment variables
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Programs variables
local terminal = "rio"
local fileManager = "thunar"
local menu = "rofi -show drun"

-- Autostart processes
hl.on("hyprland.start", function ()
    hl.exec_cmd("waybar -c " .. home .. "/.config/waybar/config.ini -s " .. home .. "/.config/waybar/style.css")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("mako")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("wl-clipboard")
    hl.exec_cmd("hypridle")
end)

-- Automatically group each new browser window onto its own workspace (starting at 3)
local browser_classes = {
    ["brave-browser"] = true,
    ["google-chrome"] = true,
    ["google-chrome-stable"] = true,
    ["chromium"] = true,
    ["chromium-browser"] = true,
    ["firefox"] = true,
    ["firefoxdeveloperedition"] = true,
    ["org.mozilla.firefox"] = true,
    ["zen"] = true,
    ["zen-browser"] = true,
    ["vivaldi-stable"] = true,
    ["microsoft-edge"] = true,
    ["microsoft-edge-stable"] = true,
}

hl.on("window.open", function (w)
    if not w or not browser_classes[w.class] then
        return
    end

    local start_ws = 3
    local max_ws = 20
    local windows = hl.get_windows()

    local used_workspaces = {}
    for _, win in ipairs(windows) do
        if win.address ~= w.address and browser_classes[win.class] then
            if win.workspace then
                used_workspaces[win.workspace.id] = true
            end
        end
    end

    local target_ws = start_ws
    for ws = start_ws, max_ws do
        if not used_workspaces[ws] then
            target_ws = ws
            break
        end
    end

    if not w.workspace or w.workspace.id ~= target_ws then
        hl.dispatch(hl.dsp.window.move({ workspace = target_ws, window = "address:" .. w.address }))
    end
end)

-- Keybindings
local mainMod = "SUPER"

-- Example binds using correct hl.dsp dispatchers and modifier + key syntax
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("warp-terminal"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(home .. "/.nix-profile/bin/nixGL " .. home .. "/.nix-profile/bin/rio > /tmp/rio_error.log 2>&1"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("brave-browser --new-window"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("brave-browser --new-window --incognito"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("google-chrome-stable --new-window"))
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("rotatesplit"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(home .. "/.local/bin/cliphist-paste.sh"))

-- Lock screen
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Switch between windows in a floating workspace
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())
hl.bind("ALT + Tab", hl.dsp.window.alter_zorder({ mode = "top" }))

-- Switch workspaces
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "previous" }))

-- Move focus
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "d" }))

-- Switch workspaces with code keybindings
for i = 1, 10 do
    local keycode = 9 + i
    hl.bind(mainMod .. " + code:" .. keycode, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + code:" .. keycode, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mouse dragging binds using hl.bind with mouse = true option
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys (volume and brightness) using repeat/locked options
hl.bind(mainMod .. " + XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { ["repeat"] = true, locked = true })
hl.bind(mainMod .. " + XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { ["repeat"] = true, locked = true })
hl.bind(mainMod .. " + XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { ["repeat"] = true, locked = true })
hl.bind(mainMod .. " + XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { ["repeat"] = true, locked = true })
hl.bind(mainMod .. " + XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { ["repeat"] = true, locked = true })
hl.bind(mainMod .. " + XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { ["repeat"] = true, locked = true })

-- Playerctl multimedia binds using locked options
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Lid close bind
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("sh -c 'hyprlock & sleep 1; hyprctl dispatch dpms off'"), { locked = true })

-- Screenshots
hl.bind("ALT + PRINT", hl.dsp.exec_cmd("grimblast --notify copy active"))
hl.bind("PRINT", hl.dsp.exec_cmd("grimblast --notify copy area"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("grimblast --notify copy screen"))

-- Window rules
hl.window_rule({
    match = { class = "^(Code|Windsurf|dev\\.zed\\.Zed|cursor)$" },
    workspace = "2 silent"
})

hl.window_rule({
    match = { class = "^(rio)$" },
    workspace = "special:magic silent"
})

hl.window_rule({
    match = { class = "^(" .. fileManager .. ")$" },
    float = true,
    center = true,
    size = { 800, 600 }
})

hl.window_rule({
    match = { class = "^(" .. terminal .. ")$" },
    float = true,
    center = true,
    size = { 1000, 800 }
})

hl.window_rule({
    match = { class = "^(localsend_app)$" },
    float = true,
    center = true,
    size = { 800, 600 }
})

hl.window_rule({
    match = { class = "^(blueman-manager)$" },
    float = true,
    center = true,
    size = { 1000, 800 }
})

hl.window_rule({
    match = { class = "^(org.telegram.desktop)$" },
    float = true,
    center = true,
    size = { 1000, 800 }
})

hl.window_rule({
    match = { class = ".*" },
    suppress_event = "maximize"
})

hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false
    },
    no_focus = true
})
